[pytest]
markers =
    unit: mark a test as a unit test.
    integration: mark a test as an integration test.
    functional: mark a test as a functional test.
    edge_case: mark a test as an edge-case test.
    slow: mark a test as a slow-running test.
    ui: mark a test as a UI test.
